# Copyright 2026 Google LLC
# Seed script for NutriCheck AI Firestore backend

from google.cloud import firestore

# Hardcode the exact GCP project ID string (DO NOT use os.getenv("GOOGLE_CLOUD_PROJECT"))
FIRESTORE_PROJECT_ID = "qwiklabs-gcp-01-60ae6014122e"

db = firestore.Client(project=FIRESTORE_PROJECT_ID)

PRODUCTS = [
    {
        "product_id": "oreo-10rs",
        "name": "Oreo Vanilla Cream Biscuits (₹10 Pack)",
        "brand": "Cadbury / Mondelez",
        "category": "Biscuits & Cookies",
        "pack_size_grams": 43.75,
        "price_inr": 10.0,
        "sugar_grams": 16.5,
        "fat_grams": 8.8,
        "protein_grams": 2.1,
        "sodium_mg": 190.0,
        "ingredients": [
            "Refined Wheat Flour (Maida)",
            "Sugar",
            "Refined Palm Oil",
            "Cocoa Solids (3.3%)",
            "Invert Sugar",
            "Leavening Agents (INS 500(ii), INS 503(ii))",
            "Emulsifier (INS 322)",
            "Edible Common Salt",
        ],
        "chemical_additives": [
            "INS 500(ii) - Sodium Bicarbonate",
            "INS 503(ii) - Ammonium Bicarbonate",
            "INS 322 - Soy Lecithin",
        ],
        "health_score": 32,
        "health_verdict": "Unhealthy - Very High Sugar & Palm Oil. Single ₹10 pack contains ~4 teaspoons of sugar (66% of recommended daily max for adults) and high saturated fat from refined palm oil.",
    },
    {
        "product_id": "lays-magic-masala-10rs",
        "name": "Lay's India's Magic Masala Potato Chips (₹10 Pack)",
        "brand": "Lay's / PepsiCo",
        "category": "Snacks & Chips",
        "pack_size_grams": 26.0,
        "price_inr": 10.0,
        "sugar_grams": 1.2,
        "fat_grams": 9.0,
        "protein_grams": 1.8,
        "sodium_mg": 230.0,
        "ingredients": [
            "Potatoes",
            "Edible Vegetable Oil (Palmolein)",
            "Spices & Condiments",
            "Salt",
            "Maltodextrin",
            "Flavor Enhancers (INS 627, INS 631)",
        ],
        "chemical_additives": [
            "INS 627 - Disodium Guanylate",
            "INS 631 - Disodium Inosinate",
        ],
        "health_score": 40,
        "health_verdict": "Unhealthy - High Sodium & Fried in Palmolein Oil. Contains artificial flavor enhancers (INS 627/631) and high sodium per serving.",
    },
    {
        "product_id": "epigamia-greek-yogurt",
        "name": "Epigamia Natural Greek Yogurt (Plain)",
        "brand": "Epigamia",
        "category": "Dairy & Healthy Snacks",
        "pack_size_grams": 85.0,
        "price_inr": 45.0,
        "sugar_grams": 3.2,
        "fat_grams": 3.0,
        "protein_grams": 7.5,
        "sodium_mg": 45.0,
        "ingredients": [
            "Pasteurized Double Toned Milk",
            "Active Yogurt Cultures (S. thermophilus, L. bulgaricus)",
        ],
        "chemical_additives": [],
        "health_score": 88,
        "health_verdict": "Healthy - Excellent Protein & Low Sugar. Zero added sugar, zero preservatives or palm oil, rich in gut-healthy probiotics.",
    },
    {
        "product_id": "nutri-choice-digestive",
        "name": "Britannia NutriChoice High Fibre Digestive Biscuits",
        "brand": "Britannia",
        "category": "Biscuits & Cookies",
        "pack_size_grams": 100.0,
        "price_inr": 30.0,
        "sugar_grams": 14.0,
        "fat_grams": 18.0,
        "protein_grams": 8.0,
        "sodium_mg": 260.0,
        "ingredients": [
            "Whole Wheat Flour (Atta 42%)",
            "Refined Wheat Flour (Maida)",
            "Sugar",
            "Refined Palm Oil",
            "Wheat Bran (4.5%)",
            "Raising Agents (INS 500(ii), INS 503(ii))",
        ],
        "chemical_additives": [
            "INS 500(ii) - Sodium Bicarbonate",
            "INS 503(ii) - Ammonium Bicarbonate",
        ],
        "health_score": 58,
        "health_verdict": "Moderate - Better than standard cream biscuits due to 42% Atta and wheat bran, but still contains added sugar and refined palm oil.",
    },
    {
        "product_id": "maggi-2min-noodles-14rs",
        "name": "Maggi 2-Minute Masala Noodles (₹14 Pack)",
        "brand": "Nestlé",
        "category": "Instant Noodles",
        "pack_size_grams": 70.0,
        "price_inr": 14.0,
        "sugar_grams": 1.5,
        "fat_grams": 9.8,
        "protein_grams": 8.0,
        "sodium_mg": 860.0,
        "ingredients": [
            "Refined Wheat Flour (Maida)",
            "Palm Oil",
            "Salt",
            "Wheat Gluten",
            "Mineral (Calcium Carbonate)",
            "Gelling Agent (INS 508)",
            "Acidity Regulators (INS 501(i), INS 500(i), INS 330)",
        ],
        "chemical_additives": [
            "INS 508 - Potassium Chloride",
            "INS 501(i) - Potassium Carbonate",
            "INS 500(i) - Sodium Carbonate",
            "INS 330 - Citric Acid",
        ],
        "health_score": 28,
        "health_verdict": "Unhealthy - Extremely High Sodium & Fried Maida. Contains 860mg sodium per pack (~43% of daily limit) and fried in refined palm oil.",
    },
    {
        "product_id": "parle-g-5rs",
        "name": "Parle-G Glucose Biscuits (₹5 Pack)",
        "brand": "Parle",
        "category": "Biscuits & Cookies",
        "pack_size_grams": 55.0,
        "price_inr": 5.0,
        "sugar_grams": 14.2,
        "fat_grams": 7.1,
        "protein_grams": 3.6,
        "sodium_mg": 110.0,
        "ingredients": [
            "Refined Wheat Flour (Maida)",
            "Sugar",
            "Refined Palm Oil",
            "Invert Sugar Syrup",
            "Raising Agents (INS 503(ii), INS 500(ii))",
            "Milk Solids",
            "Emulsifier (INS 322)",
        ],
        "chemical_additives": [
            "INS 503(ii) - Ammonium Bicarbonate",
            "INS 500(ii) - Sodium Bicarbonate",
            "INS 322 - Soy Lecithin",
        ],
        "health_score": 38,
        "health_verdict": "Unhealthy - High Refined Sugar & Palm Oil. 1 small ₹5 pack contains over 3.5 teaspoons of sugar with zero dietary fiber.",
    },
    {
        "product_id": "coca-cola-250ml",
        "name": "Coca-Cola Original Taste (250ml Pet Bottle)",
        "brand": "The Coca-Cola Company",
        "category": "Beverages & Carbonated Drinks",
        "pack_size_grams": 250.0,
        "price_inr": 20.0,
        "sugar_grams": 27.0,
        "fat_grams": 0.0,
        "protein_grams": 0.0,
        "sodium_mg": 25.0,
        "ingredients": [
            "Carbonated Water",
            "Sugar",
            "Acidity Regulator (INS 338 - Phosphoric Acid)",
            "Color (INS 150d - Caramel IV)",
            "Caffeine",
        ],
        "chemical_additives": [
            "INS 338 - Phosphoric Acid",
            "INS 150d - Caramel Color IV",
        ],
        "health_score": 15,
        "health_verdict": "Very Unhealthy - Liquid Sugar Bomb. Single 250ml bottle has 27g of pure sugar (~6.7 teaspoons), exceeding 100% of daily recommended sugar allowance.",
    },
    {
        "product_id": "amul-taaza-toned-milk",
        "name": "Amul Taaza Toned Milk (500ml Pouch)",
        "brand": "Amul",
        "category": "Dairy & Milk",
        "pack_size_grams": 500.0,
        "price_inr": 27.0,
        "sugar_grams": 23.5,
        "fat_grams": 15.0,
        "protein_grams": 16.0,
        "sodium_mg": 250.0,
        "ingredients": [
            "Pasteurized Toned Milk",
            "Vitamin A",
            "Vitamin D",
        ],
        "chemical_additives": [],
        "health_score": 85,
        "health_verdict": "Healthy - High Protein & Calcium. Natural dairy product with zero added sugar or artificial preservatives, fortified with Vitamin A & D.",
    },
    {
        "product_id": "kurkure-masala-munch-10rs",
        "name": "Kurkure Masala Munch (₹10 Pack)",
        "brand": "Kurkure / PepsiCo",
        "category": "Snacks & Namkeen",
        "pack_size_grams": 45.0,
        "price_inr": 10.0,
        "sugar_grams": 1.0,
        "fat_grams": 15.5,
        "protein_grams": 2.6,
        "sodium_mg": 410.0,
        "ingredients": [
            "Rice Meal",
            "Corn Meal",
            "Edible Vegetable Oil (Palmolein)",
            "Gram Meal",
            "Spices & Condiments",
            "Salt",
            "Citric Acid (INS 330)",
        ],
        "chemical_additives": ["INS 330 - Citric Acid"],
        "health_score": 34,
        "health_verdict": "Unhealthy - Very High Saturated Fat & Sodium. Deep fried in palmolein oil, delivering high sodium and calorie density with low micronutrient value.",
    },
    {
        "product_id": "tata-salt-1kg",
        "name": "Tata Salt Vacuum Evaporated Iodized Salt (1kg)",
        "brand": "Tata Consumer Products",
        "category": "Staples & Spices",
        "pack_size_grams": 1000.0,
        "price_inr": 28.0,
        "sugar_grams": 0.0,
        "fat_grams": 0.0,
        "protein_grams": 0.0,
        "sodium_mg": 38700.0,
        "ingredients": [
            "Vacuum Evaporated Salt",
            "Potassium Iodate",
            "Anti-caking Agent (INS 536)",
        ],
        "chemical_additives": ["INS 536 - Potassium Ferrocyanide"],
        "health_score": 70,
        "health_verdict": "Essential Staple - Consume in Moderation. Iodized salt prevents iodine deficiency. High sodium requires strict daily portion limits (max 5g salt/day).",
    },
]


def seed_database():
    collection_ref = db.collection("products")
    print(f"Seeding {len(PRODUCTS)} products into Firestore project '{FIRESTORE_PROJECT_ID}'...")
    for prod in PRODUCTS:
        doc_ref = collection_ref.document(prod["product_id"])
        doc_ref.set(prod)
        print(f"  ✓ Seeded: {prod['name']} (ID: {prod['product_id']})")
    print("Firestore seeding complete!")


if __name__ == "__main__":
    seed_database()
